[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reciprocal-ops"
version = "1.0.0"
description = "An educational IT operations framework applying relational and reciprocal principles, inspired by Dr. Jennifer Grenz's Medicine Wheel for the Planet."
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Sarosh Jamal", email = "sjamal@github.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.2.0",
    "pydantic>=2.6.0",
    "gitpython>=3.1.40"
]

[project.optional-dependencies]
dev = ["pytest>=8.0.0"]

[project.scripts]
recip = "reciprocal_ops.cli:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["src"]


[tool.setuptools.packages.find]
where = ["src"]
include = ["reciprocal_ops*"]
